### ISSUE TITLE
Should we delete closed/merged branches?

### ISSUE THREAD

**Issue by bpas247** [Chris-Johnston/Easier68k#111]
This is more of a question, but I'm curious if we should delete any closed or merged branches that we are no longer using. Although this wouldn't mean any significant increase in performance or space, it can make the repository a bit cleaner. It also doesn't result in any history lost, as long as all changes have been merged properly.

**Comment by Chris-Johnston** [comment]
Yeah, there's no reason to keep branches around after they've been merged. I believe that we were just in crunch time and forgot to clean them up.

Issue is resolved now, good catch.
