### ISSUE TITLE
Standardize the way in which OPCODEs affect the CCR

### ISSUE THREAD

**Issue by bpas247** [Chris-Johnston/Easier68k#119]
Currently, each OPCODE is left the responsibility of affecting the CCR in whichever way they need to. However, a lot of the OPCODEs affect the CCR in either the same or similar ways. EASy68k utilizes a global function to set the CCR bits, which could be a potential solution to this issue.

**Comment by pupper68k** [comment]
Would a set of functions for Set Extend, Set Negative, Set Zero, etc... work?
Could implement getters and setters for status bits, this would make code for opcodes very clear.

**Comment by bpas247** [comment]
@pupper68k Seems like a reasonable approach :+1:

**Comment by bpas247** [comment]
Resolved by #130
