### ISSUE TITLE
Immediate data: #

### ISSUE THREAD

**Issue by LinuxKid21** [Chris-Johnston/Easier68k#39]
Fully assemble, and simulate it.

**Comment by Chris-Johnston** [comment]
Also need to remember to add `$` hex and `%` binary.

**Comment by AdamuKaapan** [comment]
I've started making progress on this in the core setup branch, I've got a method for parsing immediates (obviously processing it from a file is a different story, but we have the parser set up at least)

**Comment by Chris-Johnston** [comment]
Make sure to use the keywords https://help.github.com/articles/closing-issues-using-keywords/
